
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SushiDirectoryServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/SushiDirectoryService?wsdl")
public class SushiDirectoryServiceService
    extends Service
{

    private final static URL SUSHIDIRECTORYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SUSHIDIRECTORYSERVICESERVICE_EXCEPTION;
    private final static QName SUSHIDIRECTORYSERVICESERVICE_QNAME = new QName("http://endpoint.service/", "SushiDirectoryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/SushiDirectoryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUSHIDIRECTORYSERVICESERVICE_WSDL_LOCATION = url;
        SUSHIDIRECTORYSERVICESERVICE_EXCEPTION = e;
    }

    public SushiDirectoryServiceService() {
        super(__getWsdlLocation(), SUSHIDIRECTORYSERVICESERVICE_QNAME);
    }

    public SushiDirectoryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUSHIDIRECTORYSERVICESERVICE_QNAME, features);
    }

    public SushiDirectoryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SUSHIDIRECTORYSERVICESERVICE_QNAME);
    }

    public SushiDirectoryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUSHIDIRECTORYSERVICESERVICE_QNAME, features);
    }

    public SushiDirectoryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SushiDirectoryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SushiDirectoryService
     */
    @WebEndpoint(name = "SushiDirectoryServicePort")
    public SushiDirectoryService getSushiDirectoryServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "SushiDirectoryServicePort"), SushiDirectoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SushiDirectoryService
     */
    @WebEndpoint(name = "SushiDirectoryServicePort")
    public SushiDirectoryService getSushiDirectoryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "SushiDirectoryServicePort"), SushiDirectoryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUSHIDIRECTORYSERVICESERVICE_EXCEPTION!= null) {
            throw SUSHIDIRECTORYSERVICESERVICE_EXCEPTION;
        }
        return SUSHIDIRECTORYSERVICESERVICE_WSDL_LOCATION;
    }

}
