
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.ListOfSushiDirectory;
import types.SushiDirectory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SushiDirectoryService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface SushiDirectoryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfSushiDirectory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewSushiDirectory", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewSushiDirectory")
    @ResponseWrapper(localName = "setNewSushiDirectoryResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewSushiDirectoryResponse")
    @Action(input = "http://endpoint.service/SushiDirectoryService/setNewSushiDirectoryRequest", output = "http://endpoint.service/SushiDirectoryService/setNewSushiDirectoryResponse")
    public ListOfSushiDirectory setNewSushiDirectory(
        @WebParam(name = "arg0", targetNamespace = "")
        SushiDirectory arg0);

    /**
     * 
     * @return
     *     returns types.ListOfSushiDirectory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSushiDirectory", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllSushiDirectory")
    @ResponseWrapper(localName = "getAllSushiDirectoryResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllSushiDirectoryResponse")
    @Action(input = "http://endpoint.service/SushiDirectoryService/getAllSushiDirectoryRequest", output = "http://endpoint.service/SushiDirectoryService/getAllSushiDirectoryResponse")
    public ListOfSushiDirectory getAllSushiDirectory();

}
