
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.ListOfSushi;
import types.Sushi;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SushiService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface SushiService {


    /**
     * 
     * @return
     *     returns types.ListOfSushi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSushi", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllSushi")
    @ResponseWrapper(localName = "getAllSushiResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllSushiResponse")
    @Action(input = "http://endpoint.service/SushiService/getAllSushiRequest", output = "http://endpoint.service/SushiService/getAllSushiResponse")
    public ListOfSushi getAllSushi();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfSushi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewSushi", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewSushi")
    @ResponseWrapper(localName = "setNewSushiResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewSushiResponse")
    @Action(input = "http://endpoint.service/SushiService/setNewSushiRequest", output = "http://endpoint.service/SushiService/setNewSushiResponse")
    public ListOfSushi setNewSushi(
        @WebParam(name = "arg0", targetNamespace = "")
        Sushi arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumOfSushi", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetSumOfSushi")
    @ResponseWrapper(localName = "getSumOfSushiResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetSumOfSushiResponse")
    @Action(input = "http://endpoint.service/SushiService/getSumOfSushiRequest", output = "http://endpoint.service/SushiService/getSumOfSushiResponse")
    public int getSumOfSushi();

}
