
package service.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SushiServiceService", targetNamespace = "http://endpoint.service/", wsdlLocation = "http://localhost:8080/ws02/SushiService?wsdl")
public class SushiServiceService
    extends Service
{

    private final static URL SUSHISERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SUSHISERVICESERVICE_EXCEPTION;
    private final static QName SUSHISERVICESERVICE_QNAME = new QName("http://endpoint.service/", "SushiServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws02/SushiService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUSHISERVICESERVICE_WSDL_LOCATION = url;
        SUSHISERVICESERVICE_EXCEPTION = e;
    }

    public SushiServiceService() {
        super(__getWsdlLocation(), SUSHISERVICESERVICE_QNAME);
    }

    public SushiServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUSHISERVICESERVICE_QNAME, features);
    }

    public SushiServiceService(URL wsdlLocation) {
        super(wsdlLocation, SUSHISERVICESERVICE_QNAME);
    }

    public SushiServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUSHISERVICESERVICE_QNAME, features);
    }

    public SushiServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SushiServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SushiService
     */
    @WebEndpoint(name = "SushiServicePort")
    public SushiService getSushiServicePort() {
        return super.getPort(new QName("http://endpoint.service/", "SushiServicePort"), SushiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SushiService
     */
    @WebEndpoint(name = "SushiServicePort")
    public SushiService getSushiServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.service/", "SushiServicePort"), SushiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUSHISERVICESERVICE_EXCEPTION!= null) {
            throw SUSHISERVICESERVICE_EXCEPTION;
        }
        return SUSHISERVICESERVICE_WSDL_LOCATION;
    }

}
